FROM golang:stretch as builder

WORKDIR $GOPATH/src

RUN CGO_ENABLED=0 go get -v \
    github.com/pontaoski/barista

FROM fedora:latest

WORKDIR /barista

COPY --from=builder /go/bin/barista .

COPY ../start.sh .

ADD https://github.com/Appadeia/QueryKit/archive/0.1.tar.gz .

RUN tar -xvf 0.1.tar.gz

RUN dnf -y install python3-pip python3-dnf dbus-daemon dbus-x11

RUN yes | pip3 install dbus-next

ENTRYPOINT ["/barista/start.sh"]
