FROM fedora:latest AS base

    WORKDIR /barista

    RUN dnf -y install python3-pip python3-dnf dbus-daemon dbus-x11

    RUN yes | pip3 install dbus-next

    COPY start.sh .

    ADD https://github.com/Appadeia/QueryKit/archive/0.2.tar.gz .

    RUN tar -xvf 0.2.tar.gz

FROM golang:stretch AS builder

    WORKDIR $GOPATH/src

    RUN go get -v \
        github.com/pontaoski/barista

    RUN go get -u \
        github.com/pontaoski/barista

FROM base

    WORKDIR /barista

    RUN mkdir -p /barista/barista-go/commandlib/template/

    COPY --from=builder /go/src/github.com/pontaoski/barista/barista-go/commandlib/template/* /barista/barista-go/commandlib/template/

    COPY --from=builder /go/src/github.com/pontaoski/barista/messages/* /barista/messages/

    COPY --from=builder /go/bin/barista .

    ENTRYPOINT ["/barista/start.sh"]